### ISSUE TITLE
recommendation query to match exact context only 

### ISSUE THREAD

**Issue by simonjupp** [EBISPOT/zooma#29]
Change the query to only return records that contain all fields in the query e.g. this query below should only return one result

`/recommendations/search?propertyType=origintissue&propertyValue=lung&target=samplediagnosis`

```
{
"propertiesType": [
"origintissue"
],
"propertiesValue": [
"LUNG"
],
"propertiesTypeTag": "samplediagnosis",
"propertiesValueTag": "ADENOCARCINOMA",
"tag": "http://purl.obolibrary.org/obo/NCIT_C2852",
"conf": 0.021276595,
"support": 0.0020325202,
"lift": 0.23262411,
"conviction": 0.9282874
},
```

**Comment by warrenread** [comment]
This requirement can be met within the Solr/Lucene query web interface, the negating component using a regular expressions, which excludes all documents containing any search terms not requested in the query list. Here is an example, illustrating an exclusive search on two terms each corresponding to propertyType and propertyValue:

(propertiesTypeTag:*samplediagnosis* OR propertiesValueTag:*samplediagnosis*) AND propertiesType:*origintissue* AND propertiesType:*tumortype* AND -propertiesType:/~(.*(origintissue|tumortype).*)/ AND propertiesValue:*LUNG* AND propertiesValue:*metastatic* AND -propertiesValue:/~(.*(LUNG|metastatic).*)/

Effectively the above expression is also wildcarded, so that as long as the string contains one of the terms in the query list, the document of which it is part will not be excluded from the result set.

The implementation of this kind of negating regex search within Spring is an ongoing endeavour.

**Comment by warrenread** [comment]
The Spring classes for building Solr Criteria-based queries do not seem to work well, if at all in certain regards: see the Git log message on the resolution of this ticket. I have therefore written a very simple custom query-builder. It should work well for legal queries, but will not generalise at this point to arbitrary query strings containing unexpected keys.
