### ISSUE TITLE
configure zooma to search in specific ontology

### ISSUE THREAD

**Issue by FuqiX** [EBISPOT/zooma#52]
Dear Henriette and James,

I am trying to annotate text "type 2 diabetes mellitus   disease" with terms from DOID/MONDO using ZOOMA. However, ZOOMA only finds me the EFO term for type 2 diabetes, even if I specified in the configuration that the source ontology should be DOID or MONDO. 

I tried three types of configurations: 
- c1: use only DOID and MONDO terms. It returns me the EFO term.
      The query was `https://www.ebi.ac.uk/spot/zooma/v2/api/services/annotate?propertyValue=type+2+diabetes+mellitus&propertyType=disease&filter=ontologies:[doid,mondo]`
- c2: exclude EFO as source ontology. ZOOMA still returns me the EFO term.
- c3: excluede efo as source ontology and exclude all database curations. ZOOMA returns no terms.

I am not sure if this is the ideal behavior, or can I better tune ZOOMA to find the what I am looking for? I would expect ZOOMA returns terms from all ontologies and prioritized terms with manual curation, but still, return terms from all other ontologies. Or can I say, for my use case, OLS better suits my purpose than ZOOMA?

Thanks in advance for your reply.

**Comment by henrietteharmse** [comment]
Will this be the results you are looking for?
![image](https://user-images.githubusercontent.com/32327979/99235948-6ed3b500-27ee-11eb-92a5-29f8e838681e.png)

**Comment by FuqiX** [comment]
Yes. I can now get this page by selecting _don't use any data sources_ + _specifying the target ontology_.

However, for external users, it's a bit counterintuitive, when I already provided the preferred ontology, ZOOMA still gives me another ontology. Also, many people might not be aware of the need to unselect data sources.

I wonder if it more helpful if ZOOMA provides both mapped terms with and without curated evidence by default?

**Comment by henrietteharmse** [comment]
I get the above by only specifying the target ontologies without any setting for the data sources. In particular I did **not** need to specify "do not use any data sources".

**Comment by FuqiX** [comment]
Yes, that's exactly what's in my mind! Thank you!

Not sure if other users have the same requirements. For me, Don't need to specify "do not use any data sources" will make things much easier!

**Comment by henrietteharmse** [comment]
Further information based on chat with Fuqi.
(1) searching for  "type 2 diabetes mellitus" returns correct results as shown in screenshot above.
(2) searching for  "type 2 diabetes" returns an EFO result, but this returns the result below:
![image](https://user-images.githubusercontent.com/32327979/99549466-91fa9200-29b1-11eb-8600-374495cacd55.png)
This is not the desired result as it does not come from DOID or MONDO but EFO.  However, Zooma returns this result because of the HIGH confidence score as compare to the medium confidence score obtained in search (1).
(3)  searching for  "type 2 diabetes  disease". This gives the same results as (2). This is due to no type information available on the annotations.

**Comment by henrietteharmse** [comment]
In the case of searches (2) and (3) the desired results can be achieved by selecting the "don't search any data sources" option.

**Comment by goodb** [comment]
Hi, just to chime in here that I had exactly the same experience but did not figure out how to get it to work as described above.  It is very counter-intuitive to configure the ontology sources with one ontology selected and have results returned from another ontology - especially when you know the term you are looking for is in the ontology you selected.  

I assume this is by design and makes sense for experienced EBI curators, but I think that for external or new users, the precedence given to the data source results is a little hard to understand in the current tool.  Slightly more explanation and/or UI options could really help with this.  

Thanks so much for a very useful tool!
